# Generated by Django 4.2 on 2023-04-17 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stackbase', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(related_name='question_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
